### ISSUE TITLE
Dudas Estructuras de Datos

### ISSUE THREAD

**Issue by chrisngabp** [chrisngabp/TpHaskell#1]
data Codigo = CD Data | CC Clase | CI Instancia | CF Funcion
-- Que seria codigo entonces? Archivo es un array de codigo?
-- Importacion es un codigo?

data Clase = Clase NombreClase SoloUnWhere Firma -- O array de firma?

data Instancia = Instancia TipoInstancia NombreDeDato SoloUnWhere [Funcion] -- Funcion? O son otra cosa?

data Bloque = 	Expresion Resultado | 
				LetIn [Funcion] Bloque | 
				IfThenElse Bloque Bloque Bloque | 
				Case [Bloque] |
				Do [Funcion]
-- le falta algo?

-- podria haber un ResultadoString? ResultadoInt?

**Comment by tuxArg** [comment]
> data Codigo = CD Data | CC Clase | CI Instancia | CF Funcion
> -- Que seria codigo entonces? Archivo es un array de codigo?
Código es todo lo que no es comentario. Lo vas agrupando en categorías más amplias de primer nivel (sin tabular). Básicamente podés tener un data, una clase, una instancia o una función (hay más pero no lo vimos)
> -- Importacion es un codigo?
Sí, los import son Codigo también
> 
> data Clase = Clase NombreClase SoloUnWhere Firma -- O array de firma?
Esto estaría mal porque puede no haber where (tranquilamente es posible) y dentro del where tenés... funciones. Las clases tienen firma pero con un String no es suficiente, fijate en ghci:
:i Eq
:i Functor
:i Monad
para tener ejemplos.
> 
> data Instancia = Instancia TipoInstancia NombreDeDato SoloUnWhere [Funcion] -- Funcion? O son otra cosa?
Algo así está bien, el "soloUnWhere" no, porque sabés que no hay where cuando la lista de funciones está vacía. TipoInstancia sería el nombre de la clase.
> 
> data Bloque = Expresion Resultado |
> LetIn [Funcion] Bloque |
> IfThenElse Bloque Bloque Bloque |
> Case [Bloque] |
> Do [Funcion]
> -- le falta algo?
El de Do estaría mal. dentro del Do no van funciones. Tendrías otro tipo "Do" con lo que puede ir adentro. Pero arranquen sin do y después lo agregan. 
> 
> -- podria haber un ResultadoString? ResultadoInt?
No, acá no te importa el tipo de Resultado porque es todo texto. Si ves 12 es "12". Si ves "abc", es "\"abc\""

**Comment by chrisngabp** [comment]
Buenas! Gracias por la respuesta, te parece bien asi Clase:

`
data Clase = Clase (Maybe HerenciaClase) NombreClase DefinicionClase (Maybe Where)
data HerenciaClase = [NombreClase] String 
-- puede ser algo como (Num a, Ord a) =>
data DefinicionClase = Firma (Maybe TalQue)
data TalQue = String
`

**Comment by tuxArg** [comment]
Creo que te estás sobrecomplicando.
Suficiente con que HerenciaClase sea un String y también tiene que haber un
FirmaClase (fijate que no es lo mismo "Num a" que "Monad (m :: * -> *)").
Entonces:
class Applicative m => Monad (m :: * -> *) where
-> "class Applicative m =>" Monad "Monad (m :: * -> *)" (Maybe Where)
class Eq a where
-> "" Eq "a" (Maybe Where)

**Comment by chrisngabp** [comment]
Ya actualicé todo, cualquier cosa abro otro issue con mas preguntas
